ALTER TABLE "ShopProduct" ADD COLUMN IF NOT EXISTS "weightGrams" INTEGER;
ALTER TABLE "ShopProduct" ADD COLUMN IF NOT EXISTS "lengthMm" INTEGER;
ALTER TABLE "ShopProduct" ADD COLUMN IF NOT EXISTS "widthMm" INTEGER;
ALTER TABLE "ShopProduct" ADD COLUMN IF NOT EXISTS "heightMm" INTEGER;

