
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const TELEGRAM_BOT_TOKEN = "8575014180:AAHVKypLQcCzj6NRTgY-uAqt6XPJreMENq8";
const TELEGRAM_CHAT_ID = "8575014180";

async function sendTelegramMessage(message: string) {
  try {
    const response = await fetch(`https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        chat_id: TELEGRAM_CHAT_ID,
        text: message,
        parse_mode: 'HTML',
      }),
    });

    const result = await response.json();
    if (!result.ok) {
        console.error('Telegram API Error:', result);
    }
    return result.ok;
  } catch (error) {
    console.error('Fetch Error:', error);
    return false;
  }
}

async function main() {
  console.log('🚀 Starting test order script...');

  // 1. Find a user to assign the order to
  const user = await prisma.user.findFirst();
  
  if (!user) {
    console.error('❌ No users found in database. Cannot create order.');
    return;
  }

  console.log(`👤 Found user: ${user.name} (${user.email})`);

  // 2. Create a dummy order
  const order = await prisma.order.create({
    data: {
      userId: user.id,
      status: 'pending',
      price: 1337,
      details: JSON.stringify({
        mode: 'test',
        item: 'Test 3D Model',
        note: 'This is a test order generated by the system'
      }, null, 2)
    },
    include: {
      user: true
    }
  });

  console.log(`✅ Order #${order.id} created successfully.`);

  // 3. Send Telegram notification
  const message = `
<b>📦 Тестовый заказ #${order.id}</b>

👤 <b>Клиент:</b> ${order.user.name || 'Не указано'} (${order.user.email})
📱 <b>Телефон:</b> ${order.user.phone || 'Не указан'}
💰 <b>Сумма:</b> ${order.price} ₽

📝 <b>Детали заказа:</b>
<pre>TEST ORDER GENERATED BY ADMIN</pre>
  `;

  console.log('📨 Sending Telegram notification...');
  const sent = await sendTelegramMessage(message);

  if (sent) {
    console.log('✅ Telegram message sent successfully!');
  } else {
    console.error('❌ Failed to send Telegram message.');
  }
}

main()
  .catch(e => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
